### ISSUE TITLE
Job names are missing spaces in publication.out

### ISSUE THREAD

**Issue by gsmet** [gradle/github-actions#12]
I push job names explicitly when saving the build scans:
```yaml
      - name: Save Build Scan
        if: always()
        uses: gradle/github-actions/maven-build-scan/save@v1-beta
        with:
          job-name: "Initial JDK 11 Build"
```

But when catting my `publication.out`, I end up with the following output:

```
NativeTests-VirtualThread-Messaging,success,https://ge.quarkus.io/s/unshuzksgkqmc 
KubernetesTests-JDK11Windows,success,https://ge.quarkus.io/s/zee32llhzt4kq 
GradleTests-JDK11Windows,failure,https://ge.quarkus.io/s/ylwrcacpqessg 
JVMTests-JDK11,success,https://ge.quarkus.io/s/dtvnyf6st6x4a 
JVMTests-JDK21,success,https://ge.quarkus.io/s/74h4ikqogm3h6 
NativeTests-Data4,success,https://ge.quarkus.io/s/tzgpj4jsv6vik 
```

All the spaces are missing from the job names.
